version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern_auth

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "5173:5174"
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app

volumes:
  mongo-data:
